apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: web-app
spec:
  containers:
  - name: webapp
    [cite_start]image: gcr.io/ece9016-cloudproject-group7/webapp:v1 
    ports:
    - containerPort: 5005
    env:
    - name: DB_HOST
      value: "db-service"
    - name: DB_PASSWORD
      value: "rootpassword"
    - name: DB_NAME
      value: "products_db"